name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "SALAT_TIME_REST_API"=$SALAT_TIME_REST_API > .env
        env:
          SALAT_TIME_REST_API: ${{ secrets.SALAT_TIME_REST_API }}
      - run: echo "QURAN_REST_API"=$QURAN_REST_API >> .env
        env:
          QURAN_REST_API: ${{ secrets.QURAN_REST_API }}
      - run: echo "REDIS_URL"=$REDIS_URL >> .env
        env:
          REDIS_URL: ${{ secrets.REDIS_URL_PRODUCTION }}
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME_PRODUCTION}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          usedocker: true
          docker_build_args: |
            SALAT_TIME_REST_API
            QURAN_REST_API
            REDIS_URL
        env:
          SALAT_TIME_REST_API: ${{ secrets.SALAT_TIME_REST_API }}
          QURAN_REST_API: ${{ secrets.QURAN_REST_API }}
          REDIS_URL: ${{ secrets.REDIS_URL_PRODUCTION }}
